---
title: "Internationalisation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Internationalisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The rep2si version of DieTryinSR, the android companion app used for data collection, supports full internationalisation. Every piece of text displayed in the app can be customised and shown in your preferred language.

When preparing the files for the DieTryinSR app, you will initially run `setup_folders()`. Options for this function are described in the package's README file and in the function documentation. This function will create a directory called `RICH`, which contains various files and subdirectories that you will eventually need to transfer to the android device on which you are running DieTryinSR.

Among the files generated by `setup_folders()` is `RICH/i18n.json`. Editing this file before transferring it to the android device will allow you to customise every string displayed in the app. The file uses UTF-8 character encoding, which should allow for wide coverage of different writing systems.

The file is initially populated with strings in English. At the time of writing, it contains the following fields:

```{json}
{
  "alloc_amountHint": "amount",
  "alloc_condAnon": "Anonymous",
  "alloc_condAnon_singleletter": "A",
  "alloc_condRevealed": "Revealed",
  "alloc_condRevealed_singleletter": "R",
  "alloc_endowmentLabel": "You allocate",
  "alloc_give": "You give",
  "alloc_keep": "You keep",
  "alloc_optIn": "Opt in",
  "alloc_optOut": "Opt out",
  "alloc_optOutLabel": "You keep",
  "btn_next": "Next",
  "btn_no": "No",
  "btn_save": "Save",
  "btn_yes": "Yes",
  "cancel": "Cancel",
  "checkPart": "Is this the correct participant?",
  "demoRevelations_LikertLevel1": "Not enough" ,
  "demoRevelations_LikertLevel2": "Enough",
  "demoRevelations_LikertLevel3": "More than Enough",
  "demoRevelations_LikertLevel4": "",
  "demoRevelations_LikertLevel5": "",
  "demoRevelations_DontKnow": "Don't know",
  "demoReputation_QuestionText1": "This person is generous.",
  "demoReputation_QuestionText2": "This person is fair.",
  "demoReputation_LikertLevel1": "Nope" ,
  "demoReputation_LikertLevel2": "Meh",
  "demoReputation_LikertLevel3": "Kinda",
  "demoReputation_LikertLevel4": "For sure",
  "demoReputation_LikertLevel5": "",
  "demoReputation_DontKnow": "Don't know",
  "expect": "You expect",
  "expectHint": "expected amount",
  "menu_alert_enumID": "Set enumerator ID!",
  "menu_alert_richLoc": "Set Location of RICH folder!",
  "menu_btn_allocations": "1. Allocations",
  "menu_btn_check": "Check",
  "menu_btn_demoAnon": "Demo Anon",
  "menu_btn_demoExpectation": "Demo Expectation",
  "menu_btn_demoReputation": "Demo Reputation",
  "menu_btn_demoRevealed": "Demo Revealed",
  "menu_btn_enumerator": "Enumerator",
  "menu_btn_expectations": "3. Expectations",
  "menu_btn_payout": "6. Payout",
  "menu_btn_repEval1": "2. Reputational evals I",
  "menu_btn_repEval2": "5. Reputational evals II",
  "menu_btn_report": "4. Report Allocations",
  "menu_btn_richLoc": "Rich folder Location",
  "menu_btn_setId": "Set ID",
  "menu_enumerator_label": "Enum",
  "menu_location_label": "Loc",
  "menu_partId": "Participant ID",
  "message_complete": "All decisions have been made / viewed. Looping back to first decision.",
  "message_condChange": "Next condition",
  "message_mainMenu": "Return to the main menu?",
  "message_nosettings": "No participant with this ID, or no settings for this activity. Please double check if correct ID is entered. Pay attention to capital letters if any.\n\n If there is no error in the ID you entered, please talk to the research organisers.",
  "message_setEnum": "Set enumerator ID",
  "message_setPart": "Set participant ID",
  "message_title_complete": "Complete",
  "message_title_condChange": "Condition change!",
  "message_title_mainMenu": "Main menu",
  "message_title_nosettings": "Invalid ID / Missing settings",
  "message_title_setEnum": "Enumerator ID",
  "message_title_setPart": "Participant ID",
  "message_title_wrongPart": "Stop!",
  "message_wrongPart": "Please double check if correct ID is entered. Pay attention to capital letters if any.\n\n If there is no error in the ID you entered, please ask when the participant is available next and talk to the research organisers.\n\n DO NOT CONTINUE WITH THIS PARTICIPANT NOW.",
  "ok": "Ok",
  "payout_accuracyMarginReminder": "Guesses within the following margin are consindered accurate",
  "payout_accuracyRewardReminder": "Each accurate guess is paid",
  "payout_accuracyTested": "Expectations tested for accuracy",
  "payout_accurateExpectations": "Accurate Expectations",
  "payout_grandTotal": "Grand total",
  "payout_inEdgesPayout": "Incoming allocations implemented",
  "payout_likert_label": "Which is",
  "payout_outEdgesPayout": "Outgoing allocations implemented",
  "payout_received": "Gave you",
  "payout_totalAccurateExpectations": "Total for accurate expectations",
  "payout_totalKept": "Total kept",
  "payout_totalReceived": "Total received"
}
```

To translate the app, **only edit the json values**. Leave the keys unchanged. So, for example, if you were translating the app into french, the first lines would look like this:

```{json}
{
  "alloc_amountHint": "quantité",
  "alloc_condAnon": "Anonyme",
  "alloc_condAnon_singleletter": "A",
  ...
``` 

## Keys and corresponding text in app

For the most part, the keys should be self-explanatory, and you should be easily locate the corresponding text in the app. Note the following:

- `alloc_condAnon_singleletter` and `alloc_condRevealed_singleletter` are single-letter abbreviations for the anonymous and revealed condition. In the app, they are displayed very discretely underneath the photograph of the alter.

- Strings starting with `demoRevelation` and `demoReputation` control the display of likert levels in corresponding demo screens, in the app. You almost certainly want to set these so that they correspond to the likert levels displayed in the Revelations and Reputations acitivity (these are controlled by the corresponding `build_subset_...` functions.
